### ISSUE TITLE
report error when running the demo on nano board

### ISSUE THREAD

**Issue by flycat0101** [AaronFan1992/jetson_nano_demo#1]
hi, 
when I run this demo on nano board, below error is reported:
which version is needed for numpy? my numpy version is 1.13.3.

$ python3 face_recognition/camera_demo.py
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-07-28 21:59:25.983800: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
Aborted (core dumped)

**Comment by yumaofan** [comment]
@flycat0101 You can use "pip3 install --upgrade numpy" to update your numpy version.
