### ISSUE TITLE
Performance was poor.

### ISSUE THREAD

**Issue by yichengye310** [AaronFan1992/jetson_nano_demo#3]
Unable to recognize faces. Any hint on how to improve? Thank you.

**Comment by yumaofan** [comment]
@yeyicheng Can you supply more information? This code works great for me, just FPS is a little bit slower. Did you created a "face_db" folder and put your images to it? ensure only one person in one image.

**Comment by yichengye310** [comment]
@AaronFan1992 Yes, I did. The code did box every face, but failed to recognize the person in the box. Always show unknown.
![PanJian](https://user-images.githubusercontent.com/1075777/62169784-45400300-b2f7-11e9-883d-cf4c83feb885.JPG)
<img width="960" alt="1" src="https://user-images.githubusercontent.com/1075777/62169795-4d983e00-b2f7-11e9-82a8-58dcfe068300.png">

**Comment by yichengye310** [comment]
I just changed the threshold to .4 and then the code recognized the face.

**Comment by yumaofan** [comment]
@yeyicheng It's an unreasonable approach, maybe you can create some side face images to your face_db,  or move the camera to in front of the face. lower the threshold maybe get the wrong result.

**Comment by yichengye310** [comment]
@AaronFan1992 Thank you. I will try.
