### ISSUE TITLE
Real time add faces

### ISSUE THREAD

**Issue by yichengye310** [AaronFan1992/jetson_nano_demo#4]
Hi, is it possible to add unknown faces into face_db in real time?

Thank you!

**Comment by yumaofan** [comment]
You can try to update the face_db array when running code, But I think it's means nothing Because you need to synced label the face

**Comment by yichengye310** [comment]
I am thinking of naming the new face a random name, then update it in the folder after stopping it. Can you please show me the code to update the face_db array? I tried but it says unable to feed the image into input tensor.

**Comment by tranmanhdat** [comment]
> I am thinking of naming the new face a random name, then update it in the folder after stopping it. Can you please show me the code to update the face_db array? I tried but it says unable to feed the image into input tensor.

you can open a daemon thread for updating face_db,then try update after 30s for example
