### ISSUE TITLE
FPS for performance

### ISSUE THREAD

**Issue by tranmanhdat** [AaronFan1992/jetson_nano_demo#5]
i tested on my laptop with GTX 1050 and jetson nano too,it show that the FPS increase/decrease fastly depend on how many faces in image.
i wonder why FPS changes so fastly ( 37-68 on laptop, 3-11 on jetson nano)
i calculated FPS base on 0.95* last_FPS+ 0.05*current_FPS.

**Comment by yumaofan** [comment]
In my code, I get the detected face feature one by one in order to can't out of memory, so if faces are too many would-be cost more time, 
The laptop GPU process performance is much better than jetson nano,  Of course it will be faster than nano.

**Comment by tranmanhdat** [comment]
thanks for your explanation
